targets = [ "//:oatpp-libressl" ]

[[dependency]]
package = "github.com/buckaroo-pm/oatpp"
version = "branch=master"

[[dependency]]
package = "github.com/buckaroo-pm/libressl-portable"
version = "branch=master"
private = true
