manifest = "e86ed7222da0cab8ea840daa89344966c646d3ae23dffd54d06f8573f94188a7"

[[dependency]]
package = "github.com/buckaroo-pm/libressl-portable"
target = "//:crypto"

[[dependency]]
package = "github.com/buckaroo-pm/libressl-portable"
target = "//:ssl"

[[dependency]]
package = "github.com/buckaroo-pm/libressl-portable"
target = "//:tls"

[[dependency]]
package = "github.com/buckaroo-pm/oatpp"
target = "//:oatpp"

[lock."github.com/buckaroo-pm/libressl-portable"]
versions = [ "branch=master" ]
revision = "b3560e427bca86d1a36e8de953fa043fb27587d1"

[lock."github.com/buckaroo-pm/oatpp"]
versions = [ "branch=master" ]
revision = "148e47df363ebea5b8d99476d0741a47ccf75623"

[lock."github.com/buckaroo-pm/oatpp".lock."github.com/buckaroo-pm/host-pthread"]
versions = [ "branch=master" ]
revision = "a62519aa69c8e3243d6065fbf4c1d2de072f86f6"
